services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ../../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # These variables will be populated by the entrypoint script
      - DATABASE_URL=
      - PUBLIC_SUPABASE_URL=
      - PUBLIC_SUPABASE_ANON_KEY=
      - GITHUB_CLIENT_ID=your_github_client_id
      - GITHUB_CLIENT_SECRET=your_github_client_secret
    depends_on:
      supabase:
        condition: service_healthy
    entrypoint: ["/app/dev-environment/docker/entrypoint.sh"]

  supabase:
    image: supabase/postgres:latest
    ports:
      - '54321:54321' # API Port
      - '54322:5432'   # PostgreSQL Port
    environment:
      - SUPABASE_DB_USER=supabase_user
      - SUPABASE_DB_PASSWORD=supabase_pass
      - SUPABASE_DB_NAME=supabase_db
      - SUPABASE_DB_PORT=5432
      - SUPABASE_API_PORT=54321
    volumes:
      - supabase_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:54321/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Removed the following line as the image does not recognize the 'supabase start' command
    # command: supabase start

volumes:
  supabase_data: