
source "https://rubygems.org"

gem 'jekyll-remote-theme'
gem 'github-pages', group: :jekyll_plugins
gem 'webrick'
gem 'nokogiri'
gem 'public_suffix'
gem 'dnsruby'
gem 'simpleidn'
gem 'csv'
gem 'colorator'


